name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: push
jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run node version check
        run: node -v
      - name: Run echo
        run: |
          echo Test 1
          echo Test 2
  check-node-version-2:
    runs-on: ubuntu-latest
    needs: check-node-version
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run node version check
        run: node -v
      - name: Run echo
        run: |
          echo Test 3
          echo Test 4
